CREATE TABLE agents (
  id VARCHAR(32) PRIMARY KEY,
  agent_name VARCHAR(100) NOT NULL,
  website_url VARCHAR(255) NOT NULL,
  api_key VARCHAR(255) NOT NULL,
  knowledge_base LONGTEXT,
  script_id VARCHAR(64) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);