CREATE TABLE agents (
  id INT AUTO_INCREMENT PRIMARY KEY,
  agent_id VARCHAR(32) NOT NULL UNIQUE,
  agent_name VARCHAR(100) NOT NULL,
  website_url VARCHAR(255) NOT NULL,
  provider_name VARCHAR(50) NOT NULL,
  api_key VARCHAR(255) NOT NULL,
  model_name VARCHAR(100) NOT NULL,
  knowledge_base LONGTEXT,
  script_id VARCHAR(64) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);